= Chronicle Collections Spring Utils =

== Chronicle Map ==

Chronicle Maps can be configured by setting properties in Spring. These properties correspond with the
properties the ChronicleMapBuilder class uses to create and configure a ChronicleMap.

[source, xml]
This is all you need to create a fully configured Chronicle Map
---
<bean id="map" class="com.thecitysecret.util.spring.chronicle.ChronicleMapFactoryBean">
    <constructor-arg name="keyClass" value="java.lang.Integer"/>
    <constructor-arg name="valueClass" value="java.lang.String"/>
</bean>
---

[source,xml]
In memory map
---
<bean id="map" class="com.thecitysecret.util.spring.chronicle.ChronicleMapFactoryBean">
    <constructor-arg name="keyClass" value="java.lang.Integer"/>
    <constructor-arg name="valueClass" value="java.lang.String"/>
    <property name="entries" value="3000000"/>
</bean>
---

[source, xml]
Map persisted to file
---
<bean id="map" class="com.thecitysecret.util.spring.chronicle.ChronicleMapFactoryBean">
    <constructor-arg name="keyClass" value="java.lang.Integer"/>
    <constructor-arg name="valueClass" value="java.lang.String"/>
    <property name="entries" value="3000000"/>
    <property name="dataFilePath" value="/my/data/file/path"/>
</bean>
---

The ChronicleMapBuilder documentation can be found here:

http://openhft.github.io/Chronicle-Map/apidocs/net/openhft/chronicle/map/ChronicleMapBuilder.html

== Chronicle Queue ==

Chronicle Queues can also be configured by setting properties in Spring. These properties correspond with the
properties the ChronicleQueueBuilder (Indexed & Vanilla) class uses to create and configure a ChronicleQueue.
Both builders require a String file path to be created.

[source,xml]
This is the most basic setup needed to create a Chronicle Queue (the INDEXED value can be changed to VANILLA)
---
<bean id="queue" class="com.thecitysecret.util.spring.chronicle.ChronicleQueueFactoryBean">
    <property name="path" value="/a/file/path"/>
    <property name="queueType" value="INDEXED"/>
</bean>
---

[source,xml]
The queue can be configured by passing properties to the queue bean e.g. cacheLineSize
---
<bean id="queue" class="com.thecitysecret.util.spring.chronicle.ChronicleQueueFactoryBean">
    <property name="path" value="/a/file/path"/>
    <property name="queueType" value="VANILLA"/>
    <property name="cacheLineSize" value="128"/>
</bean>
---

The ChronicleQueueBuilder documentation can be found here:

http://openhft.github.io/Chronicle-Queue/apidocs/net/openhft/chronicle/ChronicleQueueBuilder.html